"""add_brand_relationship

Revision ID: 4eddfa987e73
Revises: dd3fe36b5ffa
Create Date: 2026-01-09 09:25:22.998709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eddfa987e73'
down_revision: Union[str, Sequence[str], None] = 'dd3fe36b5ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whey_proteins', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'whey_proteins', 'brands', ['brand_id'], ['id'])
    op.drop_column('whey_proteins', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whey_proteins', sa.Column('brand', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'whey_proteins', type_='foreignkey')
    op.drop_column('whey_proteins', 'brand_id')
    # ### end Alembic commands ###
