"""add_reliability_image_url_and_brands

Revision ID: dd3fe36b5ffa
Revises: 299606e5426d_manual
Create Date: 2026-01-09 09:11:19.435678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3fe36b5ffa'
down_revision: Union[str, Sequence[str], None] = '299606e5426d_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whey_proteins', sa.Column('reliability', sa.Integer(), nullable=True))
    op.add_column('whey_proteins', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_whey_proteins_new_id'), table_name='whey_proteins')
    op.drop_index(op.f('ix_whey_proteins_new_name'), table_name='whey_proteins')
    op.create_index(op.f('ix_whey_proteins_id'), 'whey_proteins', ['id'], unique=False)
    op.create_index(op.f('ix_whey_proteins_name'), 'whey_proteins', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whey_proteins_name'), table_name='whey_proteins')
    op.drop_index(op.f('ix_whey_proteins_id'), table_name='whey_proteins')
    op.create_index(op.f('ix_whey_proteins_new_name'), 'whey_proteins', ['name'], unique=False)
    op.create_index(op.f('ix_whey_proteins_new_id'), 'whey_proteins', ['id'], unique=False)
    op.drop_column('whey_proteins', 'image_url')
    op.drop_column('whey_proteins', 'reliability')
    # ### end Alembic commands ###
